name: mypandoc
description: "It's our pandoc now John !"

dependencies:
  - base >= 4.7 && < 5
  - optparse-applicative
  - containers

library:
  source-dirs: src

executables:
  mypandoc:
    main: Main.hs
    source-dirs: app
    ghc-options: -Wall
    dependencies:
      - mypandoc
      - containers

tests:
  unit-tests:
    main: Spec.hs
    source-dirs: tests
    ghc-options: -Wall
    dependencies:
      - mypandoc
      - hspec
